
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LargeGreenhouseAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargeGreenhouseAddonDeed();
			}
		}

		[ Constructable ]
		public LargeGreenhouseAddon()
		{



			AddComplexComponent( (BaseAddon) this, 43128, 7, 5, 20, 0, -1, "Greenhouse", 1);// 1
			AddComplexComponent( (BaseAddon) this, 43107, 5, 3, 0, 0, -1, "Greenhouse", 1);// 2
			AddComplexComponent( (BaseAddon) this, 43108, 6, -2, 0, 0, -1, "Greenhouse", 1);// 3
			AddComplexComponent( (BaseAddon) this, 43113, 6, 0, 20, 0, -1, "Greenhouse", 1);// 4
			AddComplexComponent( (BaseAddon) this, 43109, 4, -5, 0, 0, -1, "Greenhouse", 1);// 5
			AddComplexComponent( (BaseAddon) this, 43108, 0, -1, 0, 0, -1, "Greenhouse", 1);// 6
			AddComplexComponent( (BaseAddon) this, 43108, 6, -3, 0, 0, -1, "Greenhouse", 1);// 7
			AddComplexComponent( (BaseAddon) this, 43114, 0, -2, 16, 0, -1, "Greenhouse", 1);// 8
			AddComplexComponent( (BaseAddon) this, 43105, 0, 0, 0, 0, -1, "Greenhouse", 1);// 9
			AddComplexComponent( (BaseAddon) this, 43105, 0, 4, 0, 0, -1, "Greenhouse", 1);// 10
			AddComplexComponent( (BaseAddon) this, 43109, 2, -5, 0, 0, -1, "Greenhouse", 1);// 11
			AddComplexComponent( (BaseAddon) this, 43106, 0, 4, 0, 0, -1, "Greenhouse", 1);// 12
			AddComplexComponent( (BaseAddon) this, 43116, 0, -4, 19, 0, -1, "Greenhouse", 1);// 13
			AddComplexComponent( (BaseAddon) this, 43116, 0, 2, 19, 0, -1, "Greenhouse", 1);// 14
			AddComplexComponent( (BaseAddon) this, 43106, -1, -5, 0, 0, -1, "Greenhouse", 1);// 15
			AddComplexComponent( (BaseAddon) this, 43122, 0, 4, 20, 0, -1, "Greenhouse", 1);// 16
			AddComplexComponent( (BaseAddon) this, 43109, 2, 0, 0, 0, -1, "Greenhouse", 1);// 17
			AddComplexComponent( (BaseAddon) this, 43113, 2, 0, 20, 0, -1, "Greenhouse", 1);// 18
			AddComplexComponent( (BaseAddon) this, 43109, 1, -5, 0, 0, -1, "Greenhouse", 1);// 19
			AddComplexComponent( (BaseAddon) this, 43106, 1, -5, 0, 0, -1, "Greenhouse", 1);// 20
			AddComplexComponent( (BaseAddon) this, 43113, 3, -1, 20, 0, -1, "Greenhouse", 1);// 21
			AddComplexComponent( (BaseAddon) this, 43113, 4, -1, 20, 0, -1, "Greenhouse", 1);// 22
			AddComplexComponent( (BaseAddon) this, 43113, 5, -1, 20, 0, -1, "Greenhouse", 1);// 23
			AddComplexComponent( (BaseAddon) this, 43113, 6, -1, 20, 0, -1, "Greenhouse", 1);// 24
			AddComplexComponent( (BaseAddon) this, 43113, 6, -2, 20, 0, -1, "Greenhouse", 1);// 25
			AddComplexComponent( (BaseAddon) this, 43113, 2, -1, 20, 0, -1, "Greenhouse", 1);// 26
			AddComplexComponent( (BaseAddon) this, 43113, 5, -4, 20, 0, -1, "Greenhouse", 1);// 27
			AddComplexComponent( (BaseAddon) this, 43109, 3, -5, 0, 0, -1, "Greenhouse", 1);// 28
			AddComplexComponent( (BaseAddon) this, 43109, 6, -5, 0, 0, -1, "Greenhouse", 1);// 29
			AddComplexComponent( (BaseAddon) this, 43113, 5, -2, 20, 0, -1, "Greenhouse", 1);// 30
			AddComplexComponent( (BaseAddon) this, 43113, 4, -2, 20, 0, -1, "Greenhouse", 1);// 31
			AddComplexComponent( (BaseAddon) this, 43113, 1, -1, 20, 0, -1, "Greenhouse", 1);// 32
			AddComplexComponent( (BaseAddon) this, 43113, 3, -2, 20, 0, -1, "Greenhouse", 1);// 33
			AddComplexComponent( (BaseAddon) this, 43113, 4, -3, 20, 0, -1, "Greenhouse", 1);// 34
			AddComplexComponent( (BaseAddon) this, 43113, 1, -2, 20, 0, -1, "Greenhouse", 1);// 35
			AddComplexComponent( (BaseAddon) this, 43109, 5, -5, 0, 0, -1, "Greenhouse", 1);// 36
			AddComplexComponent( (BaseAddon) this, 43106, 5, -5, 0, 0, -1, "Greenhouse", 1);// 37
			AddComplexComponent( (BaseAddon) this, 43114, 0, 1, 16, 0, -1, "Greenhouse", 1);// 38
			AddComplexComponent( (BaseAddon) this, 43116, 0, -1, 19, 0, -1, "Greenhouse", 1);// 39
			AddComplexComponent( (BaseAddon) this, 43113, 5, -3, 20, 0, -1, "Greenhouse", 1);// 40
			AddComplexComponent( (BaseAddon) this, 43106, 3, -5, 0, 0, -1, "Greenhouse", 1);// 41
			AddComplexComponent( (BaseAddon) this, 43113, 3, -3, 20, 0, -1, "Greenhouse", 1);// 42
			AddComplexComponent( (BaseAddon) this, 43106, 5, 0, 0, 0, -1, "Greenhouse", 1);// 43
			AddComplexComponent( (BaseAddon) this, 43106, 0, -5, 0, 0, -1, "Greenhouse", 1);// 44
			AddComplexComponent( (BaseAddon) this, 43113, 1, -3, 20, 0, -1, "Greenhouse", 1);// 45
			AddComplexComponent( (BaseAddon) this, 43109, 5, 0, 0, 0, -1, "Greenhouse", 1);// 46
			AddComplexComponent( (BaseAddon) this, 43114, 0, -3, 16, 0, -1, "Greenhouse", 1);// 47
			AddComplexComponent( (BaseAddon) this, 43108, 0, -4, 0, 0, -1, "Greenhouse", 1);// 48
			AddComplexComponent( (BaseAddon) this, 43108, 6, 0, 0, 0, -1, "Greenhouse", 1);// 49
			AddComplexComponent( (BaseAddon) this, 43113, 6, -4, 20, 0, -1, "Greenhouse", 1);// 50
			AddComplexComponent( (BaseAddon) this, 43116, 0, 3, 19, 0, -1, "Greenhouse", 1);// 51
			AddComplexComponent( (BaseAddon) this, 43114, -1, -2, 19, 0, -1, "Greenhouse", 1);// 52
			AddComplexComponent( (BaseAddon) this, 43108, 0, 1, 0, 0, -1, "Greenhouse", 1);// 53
			AddComplexComponent( (BaseAddon) this, 43108, 0, -3, 0, 0, -1, "Greenhouse", 1);// 54
			AddComplexComponent( (BaseAddon) this, 43114, -1, -3, 19, 0, -1, "Greenhouse", 1);// 55
			AddComplexComponent( (BaseAddon) this, 43113, 5, 0, 20, 0, -1, "Greenhouse", 1);// 56
			AddComplexComponent( (BaseAddon) this, 43122, -1, 4, 23, 0, -1, "Greenhouse", 1);// 57
			AddComplexComponent( (BaseAddon) this, 43105, 0, -3, 0, 0, -1, "Greenhouse", 1);// 58
			AddComplexComponent( (BaseAddon) this, 43111, -1, 1, 22, 0, -1, "Greenhouse", 1);// 59
			AddComplexComponent( (BaseAddon) this, 43105, 0, -1, 0, 0, -1, "Greenhouse", 1);// 60
			AddComplexComponent( (BaseAddon) this, 43116, 0, 1, 19, 0, -1, "Greenhouse", 1);// 61
			AddComplexComponent( (BaseAddon) this, 43113, 3, 0, 20, 0, -1, "Greenhouse", 1);// 62
			AddComplexComponent( (BaseAddon) this, 43106, 4, -5, 0, 0, -1, "Greenhouse", 1);// 63
			AddComplexComponent( (BaseAddon) this, 43126, 7, 4, 20, 0, -1, "Greenhouse", 1);// 64
			AddComplexComponent( (BaseAddon) this, 43114, 0, -1, 16, 0, -1, "Greenhouse", 1);// 65
			AddComplexComponent( (BaseAddon) this, 43113, 4, -4, 20, 0, -1, "Greenhouse", 1);// 66
			AddComplexComponent( (BaseAddon) this, 43106, 2, 0, 0, 0, -1, "Greenhouse", 1);// 67
			AddComplexComponent( (BaseAddon) this, 43114, 0, 2, 16, 0, -1, "Greenhouse", 1);// 68
			AddComplexComponent( (BaseAddon) this, 43108, 0, 3, 0, 0, -1, "Greenhouse", 1);// 69
			AddComplexComponent( (BaseAddon) this, 43105, 6, -3, 0, 0, -1, "Greenhouse", 1);// 70
			AddComplexComponent( (BaseAddon) this, 43106, 1, 0, 0, 0, -1, "Greenhouse", 1);// 71
			AddComplexComponent( (BaseAddon) this, 43105, 6, 0, 0, 0, -1, "Greenhouse", 1);// 72
			AddComplexComponent( (BaseAddon) this, 43114, -1, 2, 19, 0, -1, "Greenhouse", 1);// 73
			AddComplexComponent( (BaseAddon) this, 43108, 0, 0, 0, 0, -1, "Greenhouse", 1);// 74
			AddComplexComponent( (BaseAddon) this, 43105, 0, 3, 0, 0, -1, "Greenhouse", 1);// 75
			AddComplexComponent( (BaseAddon) this, 43114, -1, -4, 19, 0, -1, "Greenhouse", 1);// 76
			AddComplexComponent( (BaseAddon) this, 43106, 2, -5, 0, 0, -1, "Greenhouse", 1);// 77
			AddComplexComponent( (BaseAddon) this, 43111, -1, -1, 22, 0, -1, "Greenhouse", 1);// 78
			AddComplexComponent( (BaseAddon) this, 43122, -1, -5, 23, 0, -1, "Greenhouse", 1);// 79
			AddComplexComponent( (BaseAddon) this, 43114, 0, -4, 16, 0, -1, "Greenhouse", 1);// 80
			AddComplexComponent( (BaseAddon) this, 43106, 6, -5, 0, 0, -1, "Greenhouse", 1);// 81
			AddComplexComponent( (BaseAddon) this, 43106, -1, 4, 0, 0, -1, "Greenhouse", 1);// 82
			AddComplexComponent( (BaseAddon) this, 43111, -1, 0, 22, 0, -1, "Greenhouse", 1);// 83
			AddComplexComponent( (BaseAddon) this, 43107, 6, 3, 0, 0, -1, "Greenhouse", 1);// 84
			AddComplexComponent( (BaseAddon) this, 43109, 0, 4, 0, 0, -1, "Greenhouse", 1);// 85
			AddComplexComponent( (BaseAddon) this, 43108, 0, 2, 0, 0, -1, "Greenhouse", 1);// 86
			AddComplexComponent( (BaseAddon) this, 43113, 4, 0, 20, 0, -1, "Greenhouse", 1);// 87
			AddComplexComponent( (BaseAddon) this, 43122, 0, -5, 20, 0, -1, "Greenhouse", 1);// 88
			AddComplexComponent( (BaseAddon) this, 43107, 5, 4, 0, 0, -1, "Greenhouse", 1);// 89
			AddComplexComponent( (BaseAddon) this, 43105, 0, 2, 0, 0, -1, "Greenhouse", 1);// 90
			AddComplexComponent( (BaseAddon) this, 43109, 1, 0, 0, 0, -1, "Greenhouse", 1);// 91
			AddComplexComponent( (BaseAddon) this, 43114, 0, 3, 16, 0, -1, "Greenhouse", 1);// 92
			AddComplexComponent( (BaseAddon) this, 43115, -1, -5, 20, 0, -1, "Greenhouse", 1);// 93
			AddComplexComponent( (BaseAddon) this, 43116, 0, 0, 19, 0, -1, "Greenhouse", 1);// 94
			AddComplexComponent( (BaseAddon) this, 43109, 6, 0, 0, 0, -1, "Greenhouse", 1);// 95
			AddComplexComponent( (BaseAddon) this, 43108, 0, 4, 0, 0, -1, "Greenhouse", 1);// 96
			AddComplexComponent( (BaseAddon) this, 43114, 0, 4, 16, 0, -1, "Greenhouse", 1);// 97
			AddComplexComponent( (BaseAddon) this, 43114, 0, 0, 16, 0, -1, "Greenhouse", 1);// 98
			AddComplexComponent( (BaseAddon) this, 43106, 6, 0, 0, 0, -1, "Greenhouse", 1);// 99
			AddComplexComponent( (BaseAddon) this, 43113, 2, -3, 20, 0, -1, "Greenhouse", 1);// 100
			AddComplexComponent( (BaseAddon) this, 43116, 0, -3, 19, 0, -1, "Greenhouse", 1);// 101
			AddComplexComponent( (BaseAddon) this, 43108, 6, -1, 0, 0, -1, "Greenhouse", 1);// 102
			AddComplexComponent( (BaseAddon) this, 43109, -1, 4, 0, 0, -1, "Greenhouse", 1);// 103
			AddComplexComponent( (BaseAddon) this, 43116, 0, -2, 19, 0, -1, "Greenhouse", 1);// 104
			AddComplexComponent( (BaseAddon) this, 43105, 0, 1, 0, 0, -1, "Greenhouse", 1);// 105
			AddComplexComponent( (BaseAddon) this, 43113, 1, -4, 20, 0, -1, "Greenhouse", 1);// 106
			AddComplexComponent( (BaseAddon) this, 43113, 2, -4, 20, 0, -1, "Greenhouse", 1);// 107
			AddComplexComponent( (BaseAddon) this, 43105, 6, -4, 0, 0, -1, "Greenhouse", 1);// 108
			AddComplexComponent( (BaseAddon) this, 43114, -1, 3, 19, 0, -1, "Greenhouse", 1);// 109
			AddComplexComponent( (BaseAddon) this, 43113, 1, 0, 20, 0, -1, "Greenhouse", 1);// 110
			AddComplexComponent( (BaseAddon) this, 43105, 6, -2, 0, 0, -1, "Greenhouse", 1);// 111
			AddComplexComponent( (BaseAddon) this, 43105, 0, -4, 0, 0, -1, "Greenhouse", 1);// 112
			AddComplexComponent( (BaseAddon) this, 43116, 0, 4, 19, 0, -1, "Greenhouse", 1);// 113
			AddComplexComponent( (BaseAddon) this, 43114, -1, 4, 19, 0, -1, "Greenhouse", 1);// 114
			AddComplexComponent( (BaseAddon) this, 43113, 3, -4, 20, 0, -1, "Greenhouse", 1);// 115
			AddComplexComponent( (BaseAddon) this, 43115, -1, 4, 20, 0, -1, "Greenhouse", 1);// 116
			AddComplexComponent( (BaseAddon) this, 43109, 0, -5, 0, 0, -1, "Greenhouse", 1);// 117
			AddComplexComponent( (BaseAddon) this, 43113, 6, -3, 20, 0, -1, "Greenhouse", 1);// 118
			AddComplexComponent( (BaseAddon) this, 43125, 6, 4, 20, 0, -1, "Greenhouse", 1);// 119
			AddComplexComponent( (BaseAddon) this, 43109, -1, -5, 0, 0, -1, "Greenhouse", 1);// 120
			AddComplexComponent( (BaseAddon) this, 43113, 2, -2, 20, 0, -1, "Greenhouse", 1);// 121
			AddComplexComponent( (BaseAddon) this, 43108, 6, -4, 0, 0, -1, "Greenhouse", 1);// 122
			AddComplexComponent( (BaseAddon) this, 43105, 6, -1, 0, 0, -1, "Greenhouse", 1);// 123
			AddComplexComponent( (BaseAddon) this, 43127, 6, 5, 20, 0, -1, "Greenhouse", 1);// 124
			AddComplexComponent( (BaseAddon) this, 43107, 6, 4, 0, 0, -1, "Greenhouse", 1);// 125
			AddComplexComponent( (BaseAddon) this, 43115, -2, -5, 23, 0, -1, "Greenhouse", 1);// 126
			AddComplexComponent( (BaseAddon) this, 43115, -3, -5, 23, 0, -1, "Greenhouse", 1);// 127
			AddComplexComponent( (BaseAddon) this, 43119, -5, -5, 20, 0, -1, "Greenhouse", 1);// 128
			AddComplexComponent( (BaseAddon) this, 43122, -2, -5, 26, 0, -1, "Greenhouse", 1);// 129
			AddComplexComponent( (BaseAddon) this, 43111, -5, -4, 16, 0, -1, "Greenhouse", 1);// 130
			AddComplexComponent( (BaseAddon) this, 43105, -6, 3, 0, 0, -1, "Greenhouse", 1);// 131
			AddComplexComponent( (BaseAddon) this, 43108, -6, 2, 0, 0, -1, "Greenhouse", 1);// 132
			AddComplexComponent( (BaseAddon) this, 43114, -2, -2, 22, 0, -1, "Greenhouse", 1);// 133
			AddComplexComponent( (BaseAddon) this, 43105, -6, 2, 0, 0, -1, "Greenhouse", 1);// 134
			AddComplexComponent( (BaseAddon) this, 43115, -4, -5, 20, 0, -1, "Greenhouse", 1);// 135
			AddComplexComponent( (BaseAddon) this, 43105, -6, -2, 0, 0, -1, "Greenhouse", 1);// 136
			AddComplexComponent( (BaseAddon) this, 43108, -6, -1, 0, 0, -1, "Greenhouse", 1);// 137
			AddComplexComponent( (BaseAddon) this, 43106, -5, 4, 0, 0, -1, "Greenhouse", 1);// 138
			AddComplexComponent( (BaseAddon) this, 43111, -4, 4, 19, 0, -1, "Greenhouse", 1);// 139
			AddComplexComponent( (BaseAddon) this, 43114, -2, -1, 22, 0, -1, "Greenhouse", 1);// 140
			AddComplexComponent( (BaseAddon) this, 43108, -6, 1, 0, 0, -1, "Greenhouse", 1);// 141
			AddComplexComponent( (BaseAddon) this, 43115, -4, 4, 20, 0, -1, "Greenhouse", 1);// 142
			AddComplexComponent( (BaseAddon) this, 43119, -4, 4, 23, 0, -1, "Greenhouse", 1);// 143
			AddComplexComponent( (BaseAddon) this, 43106, -4, 4, 0, 0, -1, "Greenhouse", 1);// 144
			AddComplexComponent( (BaseAddon) this, 43105, -6, 0, 0, 0, -1, "Greenhouse", 1);// 145
			AddComplexComponent( (BaseAddon) this, 43106, -2, -5, 0, 0, -1, "Greenhouse", 1);// 146
			AddComplexComponent( (BaseAddon) this, 43109, -4, -5, 0, 0, -1, "Greenhouse", 1);// 147
			AddComplexComponent( (BaseAddon) this, 43109, -5, -5, 0, 0, -1, "Greenhouse", 1);// 148
			AddComplexComponent( (BaseAddon) this, 43105, -6, 1, 0, 0, -1, "Greenhouse", 1);// 149
			AddComplexComponent( (BaseAddon) this, 43114, -2, -3, 22, 0, -1, "Greenhouse", 1);// 150
			AddComplexComponent( (BaseAddon) this, 43109, -3, -5, 0, 0, -1, "Greenhouse", 1);// 151
			AddComplexComponent( (BaseAddon) this, 43109, -2, -5, 0, 0, -1, "Greenhouse", 1);// 152
			AddComplexComponent( (BaseAddon) this, 43111, -3, -2, 22, 0, -1, "Greenhouse", 1);// 153
			AddComplexComponent( (BaseAddon) this, 43111, -4, -3, 19, 0, -1, "Greenhouse", 1);// 154
			AddComplexComponent( (BaseAddon) this, 43111, -4, 0, 19, 0, -1, "Greenhouse", 1);// 155
			AddComplexComponent( (BaseAddon) this, 43114, -2, 2, 22, 0, -1, "Greenhouse", 1);// 156
			AddComplexComponent( (BaseAddon) this, 43111, -5, 3, 16, 0, -1, "Greenhouse", 1);// 157
			AddComplexComponent( (BaseAddon) this, 43111, -3, -3, 22, 0, -1, "Greenhouse", 1);// 158
			AddComplexComponent( (BaseAddon) this, 43115, -3, 4, 23, 0, -1, "Greenhouse", 1);// 159
			AddComplexComponent( (BaseAddon) this, 43114, -2, -4, 22, 0, -1, "Greenhouse", 1);// 160
			AddComplexComponent( (BaseAddon) this, 43105, -6, -3, 0, 0, -1, "Greenhouse", 1);// 161
			AddComplexComponent( (BaseAddon) this, 43114, -2, 1, 22, 0, -1, "Greenhouse", 1);// 162
			AddComplexComponent( (BaseAddon) this, 43119, -4, -5, 23, 0, -1, "Greenhouse", 1);// 163
			AddComplexComponent( (BaseAddon) this, 43107, -6, -5, 0, 0, -1, "Greenhouse", 1);// 164
			AddComplexComponent( (BaseAddon) this, 43119, -5, 4, 20, 0, -1, "Greenhouse", 1);// 165
			AddComplexComponent( (BaseAddon) this, 43111, -3, 0, 22, 0, -1, "Greenhouse", 1);// 166
			AddComplexComponent( (BaseAddon) this, 43111, -5, 1, 16, 0, -1, "Greenhouse", 1);// 167
			AddComplexComponent( (BaseAddon) this, 43114, -2, 3, 22, 0, -1, "Greenhouse", 1);// 168
			AddComplexComponent( (BaseAddon) this, 43105, -6, -4, 0, 0, -1, "Greenhouse", 1);// 169
			AddComplexComponent( (BaseAddon) this, 43111, -3, 3, 22, 0, -1, "Greenhouse", 1);// 170
			AddComplexComponent( (BaseAddon) this, 43115, -2, 4, 20, 0, -1, "Greenhouse", 1);// 171
			AddComplexComponent( (BaseAddon) this, 43111, -4, 3, 19, 0, -1, "Greenhouse", 1);// 172
			AddComplexComponent( (BaseAddon) this, 43105, -6, -1, 0, 0, -1, "Greenhouse", 1);// 173
			AddComplexComponent( (BaseAddon) this, 43111, -4, -1, 19, 0, -1, "Greenhouse", 1);// 174
			AddComplexComponent( (BaseAddon) this, 43122, -2, 4, 26, 0, -1, "Greenhouse", 1);// 175
			AddComplexComponent( (BaseAddon) this, 43106, -4, -5, 0, 0, -1, "Greenhouse", 1);// 176
			AddComplexComponent( (BaseAddon) this, 43115, -2, -5, 20, 0, -1, "Greenhouse", 1);// 177
			AddComplexComponent( (BaseAddon) this, 43119, -3, -5, 26, 0, -1, "Greenhouse", 1);// 178
			AddComplexComponent( (BaseAddon) this, 43105, -6, 4, 0, 0, -1, "Greenhouse", 1);// 179
			AddComplexComponent( (BaseAddon) this, 43111, -4, -2, 19, 0, -1, "Greenhouse", 1);// 180
			AddComplexComponent( (BaseAddon) this, 43115, -3, -5, 20, 0, -1, "Greenhouse", 1);// 181
			AddComplexComponent( (BaseAddon) this, 43114, -2, 4, 22, 0, -1, "Greenhouse", 1);// 182
			AddComplexComponent( (BaseAddon) this, 43111, -3, -4, 22, 0, -1, "Greenhouse", 1);// 183
			AddComplexComponent( (BaseAddon) this, 43111, -5, 2, 16, 0, -1, "Greenhouse", 1);// 184
			AddComplexComponent( (BaseAddon) this, 43111, -5, -1, 16, 0, -1, "Greenhouse", 1);// 185
			AddComplexComponent( (BaseAddon) this, 43109, -5, 4, 0, 0, -1, "Greenhouse", 1);// 186
			AddComplexComponent( (BaseAddon) this, 43108, -6, 4, 0, 0, -1, "Greenhouse", 1);// 187
			AddComplexComponent( (BaseAddon) this, 43108, -6, 0, 0, 0, -1, "Greenhouse", 1);// 188
			AddComplexComponent( (BaseAddon) this, 43111, -4, 1, 19, 0, -1, "Greenhouse", 1);// 189
			AddComplexComponent( (BaseAddon) this, 43106, -3, -5, 0, 0, -1, "Greenhouse", 1);// 190
			AddComplexComponent( (BaseAddon) this, 43111, -3, 4, 22, 0, -1, "Greenhouse", 1);// 191
			AddComplexComponent( (BaseAddon) this, 43111, -5, 0, 16, 0, -1, "Greenhouse", 1);// 192
			AddComplexComponent( (BaseAddon) this, 43114, -2, 0, 22, 0, -1, "Greenhouse", 1);// 193
			AddComplexComponent( (BaseAddon) this, 43108, -6, -2, 0, 0, -1, "Greenhouse", 1);// 194
			AddComplexComponent( (BaseAddon) this, 43111, -5, -2, 16, 0, -1, "Greenhouse", 1);// 195
			AddComplexComponent( (BaseAddon) this, 43119, -3, 4, 26, 0, -1, "Greenhouse", 1);// 196
			AddComplexComponent( (BaseAddon) this, 43108, -6, -3, 0, 0, -1, "Greenhouse", 1);// 197
			AddComplexComponent( (BaseAddon) this, 43111, -4, 2, 19, 0, -1, "Greenhouse", 1);// 198
			AddComplexComponent( (BaseAddon) this, 43111, -4, -4, 19, 0, -1, "Greenhouse", 1);// 199
			AddComplexComponent( (BaseAddon) this, 43115, -2, 4, 23, 0, -1, "Greenhouse", 1);// 200
			AddComplexComponent( (BaseAddon) this, 43111, -5, -3, 16, 0, -1, "Greenhouse", 1);// 201
			AddComplexComponent( (BaseAddon) this, 43115, -3, 4, 20, 0, -1, "Greenhouse", 1);// 202
			AddComplexComponent( (BaseAddon) this, 43109, -4, 4, 0, 0, -1, "Greenhouse", 1);// 203
			AddComplexComponent( (BaseAddon) this, 43106, -5, -5, 0, 0, -1, "Greenhouse", 1);// 204
			AddComplexComponent( (BaseAddon) this, 43111, -3, 1, 22, 0, -1, "Greenhouse", 1);// 205
			AddComplexComponent( (BaseAddon) this, 43111, -5, 4, 16, 0, -1, "Greenhouse", 1);// 206
			AddComplexComponent( (BaseAddon) this, 43111, -3, -1, 22, 0, -1, "Greenhouse", 1);// 207
			AddComplexComponent( (BaseAddon) this, 43108, -6, -4, 0, 0, -1, "Greenhouse", 1);// 208
			AddComplexComponent( (BaseAddon) this, 43108, -6, 3, 0, 0, -1, "Greenhouse", 1);// 209
			AddComplexComponent( (BaseAddon) this, 43111, -3, 2, 22, 0, -1, "Greenhouse", 1);// 210

		}

		public LargeGreenhouseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargeGreenhouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargeGreenhouseAddon();
			}
		}

		[Constructable]
		public LargeGreenhouseAddonDeed()
		{
			Name = "LargeGreenhouse";
		}

		public LargeGreenhouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}