
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ChristmasTree2023Addon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ChristmasTree2023AddonDeed();
			}
		}

		[ Constructable ]
		public ChristmasTree2023Addon()
		{



			AddComplexComponent( (BaseAddon) this, 40401, 1, 1, 0, 0, -1, "Presents", 1);// 1
			AddComplexComponent( (BaseAddon) this, 40400, 1, 0, 0, 0, -1, "Presents", 1);// 2
			AddComplexComponent( (BaseAddon) this, 40399, 1, -1, 0, 0, -1, "Presents", 1);// 3
			AddComplexComponent( (BaseAddon) this, 40397, 0, -1, 0, 0, -1, "Presents", 1);// 4
			AddComplexComponent( (BaseAddon) this, 40397, -1, -1, 0, 0, -1, "Presents", 1);// 5
			AddComplexComponent( (BaseAddon) this, 40398, -1, 0, 0, 0, -1, "Presents", 1);// 6
			AddComplexComponent( (BaseAddon) this, 40396, -1, 1, 0, 0, -1, "Presents", 1);// 7
			AddComplexComponent( (BaseAddon) this, 40395, 0, 1, 0, 0, -1, "Presents", 1);// 8
			AddComplexComponent( (BaseAddon) this, 40402, 0, 0, 0, 0, -1, "Christmas Tree", 1);// 9

		}

		public ChristmasTree2023Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ChristmasTree2023AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ChristmasTree2023Addon();
			}
		}

		[Constructable]
		public ChristmasTree2023AddonDeed()
		{
			Name = "ChristmasTree2023";
		}

		public ChristmasTree2023AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
